c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2015                     # [win]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2015                     # [win]
cxx_compiler_version:
  - 14.0.6                     # [osx]
  - 12                         # [linux]
clang_variant:
  - default
channels:
  - friedchickean
  - defaults
